---
# tasks file for dnsmasq

- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: present

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes

- template:
    dest: /etc/resolv.conf 
    src: resolv.conf.j2
  notify: Restart dnsmasq

- template:
    dest: /etc/dnsmasq.conf 
    src: dnsmasq.conf.j2
  notify: Restart dnsmasq

- template:
    dest: /etc/hosts.dnsmasq
    src: hosts.dnsmasq.j2
  notify: Restart dnsmasq
