---
# tasks file for dnsmasq

- name: Install dnsmasq
  yum:
    name: dnsmasq
    state: present

- name: Start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: template resolv.conf
  template:
    dest: /etc/resolv.conf 
    src: resolv.conf.j2
  notify: Restart dnsmasq

- name: template dnsmasq.conf
  template:
    dest: /etc/dnsmasq.conf 
    src: dnsmasq.conf.j2
  notify: Restart dnsmasq

- name: template hosts.dnsmasq
  template:
    dest: /etc/hosts.dnsmasq
    src: hosts.dnsmasq.j2
  notify: Restart dnsmasq

- name: template ethers
  template:
    dest: /etc/ethers
    src: ethers.j2
  notify: Restart dnsmasq

- name: add firewall rule dns
  firewalld:
    service: dns
    permanent: yes
    state: enabled
    immediate: yes

- name: add firewall rule dhcp
  firewalld:
    service: dhcp
    permanent: yes
    state: enabled
    immediate: yes