---
- name: "post intall steps for openshift 4.x"
  hosts: "localhost"
  become: false
   # variable kubeconfig_path has to be set
  # gather_facts: false
  vars:
      ansible_connection: local
      #kube_config: "{{ kubeconfig_path }}"
      kubeconfig: "{{ lookup('env','HOME') }}/.kube/config"
  roles:
    - { role: openshift-4-initial, tags: ['common'] }
