---
- name: "post intall steps for openshift 4.x"
  hosts: "localhost"
  become: false
  vars:
      kubeconfig: "{{ lookup('env','HOME') }}/.kube/config"
      htpasswd:
         local: |
           niko:$apr1$64z.beEg$qa6ua5luYoNMiY0iGR/Rq0
         demo: |
           user01:$apr1$VRlWl6KQ$wKj9FeNdCoZdeFATiMcMB0
           user02:$apr1$ek4kUSDW$gt3G6PqP8ti5tlajM/3Mi.
      ocp_admin_users:
           - niko
  roles:
      - {role: openshift-4-initial}


# print to stdout
# htpasswd -nb kubeadmin <urpasswd>
