---
- name: "post intall steps for openshift 4.x"
  hosts: "localhost"
  gather_facts: false
  connection: local
  become: false
  vars:
    kubeconfig: "{{ lookup('env','HOME') }}/.kube/config"
  vars_files:
    - techdata-auth.yaml
  roles:
    - {role: openshift-4-initial}
