---
- name: "post intall steps for openshift 4.x"
  hosts: "localhost"
  become: false
  vars:
      ansible_connection: local
      kubeconfig: "{{ lookup('env','HOME') }}/.kube/config"
      htpasswd: |
        niko:$apr1$8i60HRd7$VDcQmVdF42Cl7f9k/eLc51
      ocp_admin_users:
          - niko
  roles:
      - {role: openshift-4-initial}


# print to stdout
# htpasswd -nb kubeadmin <urpasswd>
