
- name: Create htpasswd secret
  tags: auth,htpasswd
  k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: v1
      data:
        htpasswd: "{{ htpasswd | b64encode }}"
      kind: Secret
      metadata:
        name: htpasswd
        namespace: openshift-config
      type: Opaque


- name: Create htpasswd identity provider template
  tags: auth,htpasswd
  set_fact:
    htpasswd_idp:
      htpasswd:
        fileData:
          name: htpasswd
      mappingMethod: claim
      name: HTPasswd-Locale
      type: HTPasswd


- name: Push htpasswd_idp to identity_providers
  tags: auth,htpasswd
  set_fact:
    identity_roviders: "{{ identity_roviders }} + [ {{ htpasswd_idp }} ]"

###  todo add more providers

- name: Configure identity providers
  tags: auth
  k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders: "{{ identity_roviders }}"

- name: Add cluster-admin role to admins
  tags: auth
  k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      kind: ClusterRoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: "{{ item }}-cluster-admin"
      subjects:
      - apiGroup: rbac.authorization.k8s.io
        kind: User
        name: "{{ item }}"
      roleRef:
        kind: ClusterRole
        name: "cluster-admin"
  with_items: "{{ocp_admin_users}}"
