# install and configure ibm-block-csi operator
---
- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: "{{ kube_storage_namespace }}"
  tags:
    - storage
    - ibm

- name: "install operator"
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ kube_storage_namespace }}"
    template:
      crds/1.7.0/ibm-block-csi-operator.yaml.j2
  register: operators
  tags:
    - storage
    - ibm



- name: Wait for operator pods to start
  shell: oc get pod -l app.kubernetes.io/name=ibm-block-csi-operator  -n "{{ kube_storage_namespace }}" | grep -E "(1/1|2/2).*Running" | wc -l
  register: podsrunning
  until: " '1' in podsrunning.stdout"
  retries: 120
  delay: 2
  changed_when: false
  tags: 
    - storage
    - ibm
  

- name: Print operator pod status
  ansible.builtin.debug: 
    msg: "pods running: {{podsrunning}}"


