---
# initial tasks for openshift4
# ------------------------------------------------------------------------------
# Configure authentication
# ------------------------------------------------------------------------------
- set_fact:
    identity_roviders: "[]"
  tags: auth


- debug:
    msg: " Kube config path: {{ kubeconfig }}"


- fail: msg="The variable 'kubeconfig' is not defined"
  when: kubeconfig is undefined


- import_tasks: htpasswd-provider.yaml
  tags: auth,htpasswd
