---
# initial tasks for openshift4
# ------------------------------------------------------------------------------
# Configure authentication
# ------------------------------------------------------------------------------
- set_fact:
    identity_roviders: "[]"
  tags: auth


- debug:
    msg: " Kube config path: {{ kubeconfig_path }}"


- fail: msg="The variable 'kubeconfig_path' is not defined"
  when: kubeconfig_path is undefined


- import_tasks: approve-crd.yaml
  tags:
     - cert
  #when: htpasswd is changed
